{"name": "test_write_review", "status": "failed", "statusDetails": {"message": "AssertionError: Cant find element by locator: ('css selector', '#content > div > div.col-sm-4 > div.rating > p > a:nth-child(7)')", "trace": "self = <page_objects.ProductPage.ProductPage object at 0x101be81f0>, locator = ('css selector', '#content > div > div.col-sm-4 > div.rating > p > a:nth-child(7)')\n\n    def _verify_element_presence(self, locator: tuple):\n        try:\n>           return WebDriverWait(self.browser, self.browser.t).until(EC.visibility_of_element_located(locator))\n\npage_objects/BasePage.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"fe71aecbacb444145bd921c82e68849d\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x101a94280>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       0   chromedriver                        0x00000001013fad98 chromedriver + 4337048\nE       1   chromedriver                        0x00000001013f2e14 chromedriver + 4304404\nE       2   chromedriver                        0x000000010101fa5c chromedriver + 293468\nE       3   chromedriver                        0x0000000101064d50 chromedriver + 576848\nE       4   chromedriver                        0x000000010109f908 chromedriver + 817416\nE       5   chromedriver                        0x0000000101058a5c chromedriver + 526940\nE       6   chromedriver                        0x0000000101059908 chromedriver + 530696\nE       7   chromedriver                        0x00000001013c0de4 chromedriver + 4099556\nE       8   chromedriver                        0x00000001013c52a0 chromedriver + 4117152\nE       9   chromedriver                        0x00000001013cb52c chromedriver + 4142380\nE       10  chromedriver                        0x00000001013c5da0 chromedriver + 4119968\nE       11  chromedriver                        0x000000010139da74 chromedriver + 3955316\nE       12  chromedriver                        0x00000001013e2a48 chromedriver + 4237896\nE       13  chromedriver                        0x00000001013e2bc4 chromedriver + 4238276\nE       14  chromedriver                        0x00000001013f2a8c chromedriver + 4303500\nE       15  libsystem_pthread.dylib             0x000000018cafffa8 _pthread_start + 148\nE       16  libsystem_pthread.dylib             0x000000018cafada0 thread_start + 8\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:89: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nbrowser = <selenium.webdriver.remote.webdriver.WebDriver (session=\"fe71aecbacb444145bd921c82e68849d\")>\n\n    def test_write_review(browser):\n        MainPage(browser).go_to_product_page()\n>       review = ProductPage(browser).click_review()\n\ntests/test_opencart.py:78: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npage_objects/ProductPage.py:23: in click_review\n    review = self._element(self.REVIEW)\npage_objects/BasePage.py:27: in _element\n    return self._verify_element_presence(locator)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page_objects.ProductPage.ProductPage object at 0x101be81f0>, locator = ('css selector', '#content > div > div.col-sm-4 > div.rating > p > a:nth-child(7)')\n\n    def _verify_element_presence(self, locator: tuple):\n        try:\n            return WebDriverWait(self.browser, self.browser.t).until(EC.visibility_of_element_located(locator))\n        except TimeoutException:\n>           raise AssertionError(\"Cant find element by locator: {}\".format(locator))\nE           AssertionError: Cant find element by locator: ('css selector', '#content > div > div.col-sm-4 > div.rating > p > a:nth-child(7)')\n\npage_objects/BasePage.py:24: AssertionError"}, "start": 1695470675121, "stop": 1695470680582, "uuid": "3d12ec1f-87aa-4977-acdf-795b138d2b52", "historyId": "90a05bce4209fc9b9e687dfa0748c42f", "testCaseId": "90a05bce4209fc9b9e687dfa0748c42f", "fullName": "tests.test_opencart#test_write_review", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_opencart"}, {"name": "host", "value": "Karinas-MacBook-Air.local"}, {"name": "thread", "value": "63199-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_opencart"}]}